title: Miles Williams
description: Ph.D. Candidate in Political Science at the University of Illinois at Urbana-Champaign
logo: https://raw.githubusercontent.com/milesdwilliams15/job-market-materials/main/logo.png?token=AFTKJUS5OPEAVUX5EZCRY3TAZS5JO
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
gems:
  - jekyll-mentions
    
