title: Miles D. Williams
description: PhD Candidate in Political Science at UIUC | Associate Fellow with OES
logo: "https://avatars.githubusercontent.com/u/23504082?s=400&u=aa5bd54e36a65e310dad984963379bac5a49108f&v=4"
google_analytics: true
show_downloads: true
theme: jekyll-theme-minimal
baseurl: ""
url: "https://milesdwilliams15.github.io/"
gems:
  - jekyll-mentions
  - jekyll-sitemap
