title: Miles Williams
description: Ph.D. Candidate in Political Science at the University of Illinois at Urbana-Champaign
logo: milesdwilliams15/job-market-materials/logo.png
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
gems:
  - jekyll-mentions
    
