title: Miles D. Williams
description: Ph.D. Student, University of Illinois at Urbana-Champaign
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  
email:
  id: 'milesdw2@illinois.edu'
  href: 'mailto:'
  title: 'Email'
  fa-icon: 'fa-envelope-square'
  
github:
  id: 'milesdwilliams15'
  href: 'https://github.com/'
  title: 'GitHub'
  fa-icon: 'fa-github-square'
