title: Miles Williams
description: Ph.D. Candidate in Political Science at the University of Illinois at Urbana-Champaign
logo: https://github.com/milesdwilliams15/job-market-materials/blob/main/logo.png?raw=true
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal
gems:
  - jekyll-mentions
    
